ping_cluster_1 = {
    gcp_project_id = "telus-315414"
    cluster_type = "zonal"
    cluster_location = "us-west1-a"
    cluster_name = "ping-cluster-1"
    gcp_and_k8s_sa_names = "ping-cluster-1"
    k8s_namespace = "test"
    k8s_namespace_to_create = "test"
    roles = "roles/storage.admin,roles/compute.admin"
    nodes_ip_cidr_range = "10.1.0.0/16"
    pods_ip_cidr_range = "192.168.1.0/24"
    svcs_ip_cidr_range = "192.168.3.0/24"
    machine_type = "n1-standard-1"
    initial_node_count = "1"
    workload_identity_enabled = "true"
}

ping_cluster_2 = {
    gcp_project_id = "telus-315414"
    cluster_type = "regional"
    cluster_location = "northamerica-northeast1"
    cluster_name = "ping-cluster-2"
    gcp_and_k8s_sa_names = "ping-cluster-2"
    k8s_namespace = "test"
    k8s_namespace_to_create = "test"
    roles = "roles/storage.admin,roles/compute.admin"
    nodes_ip_cidr_range = "10.2.0.0/16"
    pods_ip_cidr_range = "192.168.2.0/24"
    svcs_ip_cidr_range = "192.168.4.0/24"
    machine_type = "n1-standard-1"
    initial_node_count = "1"
    workload_identity_enabled = "true"
}